local M = {}

---@param c table<string, string> palette
---@return table<string, vim.api.keyset.highlight>
local function groups(c)
  return {
    -- editor
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.fg, bg = c.float },
    FloatBorder = { fg = c.menu_sel, bg = c.float },
    FloatTitle = { fg = c.bg, bg = c.status, bold = true },
    Cursor = { fg = c.bg, bg = c.white },
    lCursor = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    CursorLine = { bg = c.grey2 },
    CursorColumn = { bg = c.grey2 },
    ColorColumn = { bg = c.grey2 },
    LineNr = { fg = c.line_nr, bg = c.grey1 },
    CursorLineNr = { fg = c.gold, bg = c.grey1, bold = true },
    SignColumn = { bg = c.grey1 },
    Folded = { fg = c.fold_fg, bg = c.indigo },
    FoldColumn = { link = "Folded" },
    WinSeparator = { fg = c.grey3 },
    VertSplit = { link = "WinSeparator" },
    StatusLine = { fg = c.bg, bg = c.status, bold = true },
    StatusLineNC = { fg = "#444444", bg = "#AAAAAA" },
    WinBar = { fg = c.fg, bold = true },
    WinBarNC = { fg = c.grey5 },
    TabLine = { fg = c.grey6, bg = c.grey2, underline = true },
    TabLineSel = { fg = c.white, bg = c.bg },
    TabLineFill = { fg = c.grey6, bg = c.grey5, underline = true },
    Visual = { bg = c.visual },
    VisualNOS = { bg = "#444444" },
    Search = { bg = c.grey4 },
    IncSearch = { fg = c.bg, bg = c.yellow },
    CurSearch = { link = "IncSearch" },
    Substitute = { link = "IncSearch" },
    MatchParen = { bg = c.paren },
    NonText = { fg = c.grey3 },
    SpecialKey = { fg = c.grey3 },
    Whitespace = { fg = c.grey3 },
    EndOfBuffer = { fg = c.grey3 },
    Conceal = { fg = c.grey5 },
    Directory = { link = "Identifier" },
    Title = { fg = c.magenta, bold = true },
    ErrorMsg = { fg = c.white, bg = "#FF0000" },
    WarningMsg = { fg = c.red },
    MoreMsg = { fg = "#00AA00" },
    Question = { link = "MoreMsg" },
    ModeMsg = { fg = c.fg, bold = true },
    MsgArea = { fg = c.fg },
    WildMenu = { fg = c.bg, bg = c.yellow, bold = true },
    QuickFixLine = { bg = c.indigo },
    Pmenu = { fg = c.white, bg = c.menu, bold = true },
    PmenuSel = { fg = c.white, bg = c.menu_sel, bold = true },
    PmenuSbar = { bg = c.grey5 },
    PmenuThumb = { bg = c.white },
    PmenuKind = { fg = c.cyan, bg = c.menu },
    PmenuKindSel = { fg = c.cyan, bg = c.menu_sel },
    PmenuExtra = { fg = c.periwinkle, bg = c.menu },
    PmenuExtraSel = { fg = c.white, bg = c.menu_sel },
    PmenuMatch = { fg = c.gold, bg = c.menu, bold = true },
    PmenuMatchSel = { fg = c.gold, bg = c.menu_sel, bold = true },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.menu_sel, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },
    SpellLocal = { sp = c.teal, undercurl = true },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { fg = "#803030", bg = c.diff_delete },
    DiffText = { bg = c.diff_text, bold = true },

    -- syntax
    Comment = { fg = c.purple },
    Constant = { fg = c.teal },
    String = { fg = c.green },
    Character = { link = "Constant" },
    Number = { link = "Constant" },
    Boolean = { link = "Constant" },
    Float = { link = "Constant" },
    Identifier = { fg = c.gold },
    Function = { link = "Identifier" },
    Statement = { fg = c.orange },
    Conditional = { link = "Statement" },
    Repeat = { link = "Statement" },
    Label = { link = "Statement" },
    Operator = { link = "Statement" },
    Keyword = { link = "Statement" },
    Exception = { link = "Statement" },
    PreProc = { fg = c.cyan },
    Include = { link = "PreProc" },
    Define = { link = "PreProc" },
    Macro = { link = "PreProc" },
    PreCondit = { link = "PreProc" },
    Type = { fg = c.khaki },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = c.moss },
    SpecialChar = { link = "Special" },
    Tag = { link = "Special" },
    Delimiter = { link = "Special" },
    SpecialComment = { link = "Special" },
    Debug = { link = "Special" },
    Regexp = { fg = c.sky },
    Underlined = { fg = c.sky, underline = true },
    Ignore = { fg = c.bg },
    Error = { fg = c.white, bg = "#FF0000" },
    Todo = { fg = c.gold, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.periwinkle },
    Removed = { fg = c.orange },
    diffAdded = { link = "Added" },
    diffRemoved = { link = "Removed" },
    diffChanged = { link = "Changed" },
    diffLine = { link = "PreProc" },
    diffSubname = { link = "Comment" },
    diffFile = { fg = c.gold },
    diffIndexLine = { fg = c.khaki },

    -- treesitter. Old regex syntax files left most of the buffer unhighlighted,
    -- which is a big part of vividchalk's look, so plain variables, members,
    -- operators and punctuation all stay the foreground color.
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { link = "Constant" },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.parameter.builtin"] = { link = "Constant" },
    ["@variable.member"] = { fg = c.fg },
    ["@variable.member.ruby"] = { link = "Identifier" }, -- @ivars
    ["@property"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "PreProc" },
    ["@module"] = { link = "Type" },
    ["@module.builtin"] = { link = "Type" },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "Comment" },
    ["@string.regexp"] = { link = "Regexp" },
    ["@string.escape"] = { link = "Special" },
    ["@string.special"] = { link = "Special" },
    ["@string.special.symbol"] = { link = "Constant" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "Special" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Type" },
    ["@attribute"] = { link = "@function.macro" },
    ["@attribute.builtin"] = { link = "@function.macro" },
    ["@function"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@function.macro"] = { fg = c.periwinkle },
    ["@constructor"] = { link = "Type" },
    ["@constructor.lua"] = { fg = c.fg }, -- table braces
    ["@operator"] = { fg = c.fg },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.special"] = { link = "Special" }, -- #{interpolation}
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { fg = c.periwinkle, bold = true },
    ["@comment.warning"] = { fg = c.orange, bold = true },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.quote"] = { link = "Type" },
    ["@markup.math"] = { link = "Constant" },
    ["@markup.link"] = { fg = c.sky },
    ["@markup.link.label"] = { fg = c.sky },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.block"] = { fg = c.fg },
    ["@markup.list"] = { link = "Statement" },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.grey5 },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { link = "Statement" },
    ["@tag.builtin"] = { link = "Statement" },
    ["@tag.attribute"] = { link = "Type" },
    ["@tag.delimiter"] = { link = "Identifier" },

    -- LSP semantic tokens outrank both treesitter and regex syntax. The cleared
    -- groups let whatever is underneath show through. Servers call anything
    -- callable a function, which would flatten treesitter's builtins and
    -- decorators into plain calls.
    ["@lsp.type.function"] = {},
    ["@lsp.type.method"] = {},
    ["@lsp.type.variable"] = {},
    ["@lsp.type.property"] = {},
    ["@lsp.type.comment"] = {},
    ["@lsp.type.string"] = {},
    ["@lsp.type.keyword"] = {},
    ["@lsp.type.operator"] = {},
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    -- rust-analyzer
    ["@lsp.type.const"] = { link = "@constant" },
    ["@lsp.type.derive"] = { link = "Type" },
    ["@lsp.type.selfTypeKeyword"] = { link = "@type.builtin" },
    ["@lsp.type.lifetime"] = { link = "Special" },
    ["@lsp.type.formatSpecifier"] = { link = "Special" },
    ["@lsp.type.escapeSequence"] = { link = "Special" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },

    -- diagnostics and LSP
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.gold },
    DiagnosticInfo = { fg = c.periwinkle },
    DiagnosticHint = { fg = c.teal },
    DiagnosticOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red, bg = c.grey1 },
    DiagnosticSignWarn = { fg = c.gold, bg = c.grey1 },
    DiagnosticSignInfo = { fg = c.periwinkle, bg = c.grey1 },
    DiagnosticSignHint = { fg = c.teal, bg = c.grey1 },
    DiagnosticSignOk = { fg = c.green, bg = c.grey1 },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.gold, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.periwinkle, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.teal, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticUnnecessary = { fg = c.grey5 },
    DiagnosticDeprecated = { strikethrough = true },
    LspReferenceText = { bg = c.diff_change },
    LspReferenceRead = { bg = c.diff_change },
    LspReferenceWrite = { bg = c.diff_text },
    LspSignatureActiveParameter = { fg = c.gold, bold = true },
    LspInlayHint = { fg = c.grey5 },
    LspCodeLens = { fg = c.grey5 },

    -- telescope
    TelescopeNormal = { fg = c.fg, bg = c.bg },
    TelescopeBorder = { fg = c.menu_sel, bg = c.bg },
    TelescopeTitle = { link = "FloatTitle" },
    TelescopePromptPrefix = { fg = c.orange },
    TelescopePromptCounter = { fg = c.grey5 },
    TelescopeSelection = { bg = c.grey2 },
    TelescopeSelectionCaret = { fg = c.orange, bg = c.grey2 },
    TelescopeMultiSelection = { fg = c.lime },
    TelescopeMatching = { fg = c.gold, bold = true },

    -- which-key
    WhichKey = { fg = c.gold },
    WhichKeyGroup = { fg = c.orange },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.grey4 },
    WhichKeyValue = { fg = c.grey5 },

    -- mini.files
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { fg = c.orange, bg = c.float },
    MiniFilesTitle = { fg = c.grey6, bg = c.float },
    MiniFilesTitleFocused = { link = "FloatTitle" },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { fg = c.fg },
    MiniFilesCursorLine = { bg = c.grey2 },

    -- lazy.nvim / mason
    LazyNormal = { link = "NormalFloat" },
    MasonNormal = { link = "NormalFloat" },
  }
end

local function terminal(c)
  local colors = {
    c.bg, c.red, c.green, c.gold, c.menu_sel, c.purple, c.teal, c.grey6,
    c.grey4, c.orange, c.lime, c.yellow, c.periwinkle, c.magenta, c.cyan, c.white,
  }
  for i, color in ipairs(colors) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

function M.load()
  if vim.g.colors_name then
    vim.cmd.highlight("clear")
  end
  -- changing 'background' re-sources the colorscheme, so only touch it if needed
  if vim.o.background ~= "dark" then
    vim.o.background = "dark"
  end
  vim.o.termguicolors = true
  vim.g.colors_name = "neochalk"

  local c = require("neochalk.palette")
  for name, hl in pairs(groups(c)) do
    vim.api.nvim_set_hl(0, name, hl)
  end
  terminal(c)
end

return M
